### PR TITLE
[Labyrinth-Escape] Web based RADI-v2.4

### PR DESCRIPTION
**Pull request by iamarkaj**
closes issue #1019

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
- I couldn't see Labyrinth-Escape in RoboticsAcademy.html. Have you included it in the server (sqtlite) and committed those changes?
- Arrows dir is not used. It should be removed in ROSnode and web-template releases.

**Comment by iamarkaj** [comment]
Here are the steps I followed to add new exercise:
1. Open 0.0.0.0/admin and add new exercise
2. python3 manage.py makemigrations
3. python3 migrate

Am I missing something? Any help will be appreciated

**Comment by pariaspe** [comment]
It is working but it takes a lot to connect  and the world displayed doesn't have the new labyrinth model in it.

lab

**Comment by iamarkaj** [comment]
Since simple_labyrinth_green was just added yesterday in the drones repo. It will work after the new release of jderobot-drones but currently, you need to add the simple_labyrinth_green model inside /opt/ros/melodic/share/drone_assets/models
It is taking a long time because it cannot find the model.

**Comment by pariaspe** [comment]
Model missing fixed in #1037. Exercise is working properly

**Pull request merged**
