### PR TITLE
[FollowTurtlebot] add developer launching instructions

### PR DESCRIPTION
**Pull request by iamarkaj**
issue #806

### CODE REVIEW

**Comment by pariaspe** [comment]
Hi @iamarkaj,

The PR seems to be OK, but, before merging, what is the purpose of the _dev_ checkbox?

**Review by pariaspe — APPROVED** [review]

**Comment by iamarkaj** [comment]
Hi @pariaspe 
It is used inside launcher.js to skip opening the exercise again, otherwise all the threads will be killed immediately
```
if (!dev_mode.checked) {
      console.log("user-mode")
      ws_manager = new WebSocket("ws://" + websocket_address + ":8765/");
      exercise = "follow_turtlebot"

      ws_manager.onopen = function (event) {
          var size = get_novnc_size();
          ws_manager.send(JSON.stringify({"command": "exit", "exercise": ""}))
          ws_manager.send(JSON.stringify({"command": "open", "exercise": exercise, "width": size.width.toString(), "height": size.height.toString()}));
      }

      ws_manager.onmessage = function (event) {
          console.log(event.data);
      }
}
```

**Comment by pariaspe** [comment]
I'm merging it, but I'm not sure if the checkbox is a wanted feature. Thanks @iamarkaj

**Comment by iamarkaj** [comment]
Hi @pariaspe 
This video is a demonstration of when we run without the checkbox. Do let me know if this helps.

https://user-images.githubusercontent.com/40225765/115850459-7f462680-a443-11eb-94a8-a8e489c26d58.mp4

**Pull request merged**
