### PR TITLE
Merge GUI windows of Color Filter Exercise

### PR DESCRIPTION
**Pull request by nemathahmed**
Hi,
This is in reference to #481 
What I've done --
- Merge the Main, Camera, Color Filter and Detector windows to on window. 
- Update the documentation.
- Add theory, hints, video demo for the exercise.
- Changes in cameraSegment.py to maintain the aspect ratio of portrait video(*in case used*)
- Clean up the redundant files(such as camera widget, detector widget, color filter widget as all these widgets are now merged into one)

The final GUI window now looks like this:

guidemo

### CODE REVIEW

**Comment by jmplaza** [comment]
Hi @nemathahmed,

the resources (colorspace.jpg and guidemo.png) should not be on the exercises directory, but in the docs directory. They are part of the exercise documentation, not of the source code. Take a look at the documentation of other exercises (as in https://github.com/JdeRobot/RoboticsAcademy/tree/master/docs/assets/images/exercises/follow_line)

In addition, the documentation should not be in the README.md file, just on its webpage, in the docs/ directory (as in https://github.com/JdeRobot/RoboticsAcademy/tree/master/docs/_pages/exercises/ComputerVision). We use GitHub Pages for the documentation. Take a look at the webpages of other exercises. I would suggest to remove any documentation file from this pull-request, to focus it on solving the exercise source code template. Improving the exercise documentation (its webpage) would deserve a separate issue and a separate pull-request.

**Comment by nemathahmed** [comment]
Hello @jmplaza 
Sorry for the slight misunderstanding from my side.
I've made the changes:
- Update the README.md to just have the instructions to run the exercise.
- Delete the two image files(colorspace.jpg and guidemo.png) from the *resources* directory.

**Comment by jmplaza** [comment]
HI @nemathahmed , good step forward. Ideally the README.md should include ONLY a link to the exercise webpage (which it has not been created yet). This way the instructions for launching the exercise are stored on a single place, which is easier to maintain

**Comment by nemathahmed** [comment]
Hello @jmplaza, I have replaced the README.md file with only a link to the exercise webpage and have created a new exercise webpage under issue #526.
Thanks,
Nemath

**Pull request merged**
