### PR TITLE
Dockerfile cleaning

### LINKED ISSUE #1549: Cleaning Dockerfiles
## To do:
- Review drones and stdr installation
- Review exposed ports

## To explore:
- STDR files copy are needed?
- Move manager env vars to ENV cmds
- Echos --> is bashrc executed on entrypoint?

### PR DESCRIPTION
**Pull request by pariaspe**
Closes #1549

### CODE REVIEW

**Comment by pariaspe** [comment]
Logging may still not work. Ports exposed need to be explained in Dockerfile.
Major testing is needed before merging.

**Comment by iamarkaj** [comment]
Hi @pariaspe 
I was checking this PR but the .env file is missing
```
Step 13/31 : COPY .env /
COPY failed: file not found in build context or excluded by .dockerignore: stat .env: file does not exist
```

**Comment by pariaspe** [comment]
Fix on [cb3ec9c](https://github.com/JdeRobot/RoboticsAcademy/pull/1560/commits/cb3ec9c52fe6ff90964612a91395ce173ba22915). Thanks @iamarkaj, I missed it due to gitignore

**Comment by iamarkaj** [comment]
Command to run RADI with logging (after PR #1591 is merged)
```
docker run -it --rm -v $HOME/.roboticsacademy/log/:/root/.roboticsacademy/log/ -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy:3.2 --logs
```

**Comment by dvalladaresv** [comment]
Amazing work!

**Pull request merged**
