### PR TITLE
Restructured install and launch docs

### PR DESCRIPTION
**Pull request by pawanw17**
#1963 Unified RADI install and launching instructions for all exercises except the ones that require a camera parameter to launch.
[Color Filter](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/color_filter),
[Human Detection](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/human_detection)
[Digit Classifier](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/dl_digit_classifier)
[Optical Flow Teleop](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/opticalflow_teleop)

I am unable to launch these exercises correctly #1973 . Hence refrained from updating their docs yet.

A few exercises like [vacuum cleaner](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/vacuum_cleaner) required cloning the git repository. Is that still required? @jmplaza @pariaspe

### CODE REVIEW

**Comment by pariaspe** [comment]
Hi, I'll take a look. No, cloning the repo is not required anymore. Thanks for the PR

**Comment by pawanw17** [comment]
> * List of exercises modified seems good to me.
> * We can take advantage of the changes and add to these exercises the new RAM port (7163).
> * To my eyes, I think the proposed instructions says too little. I would write something like:
> 
> ### Installation
> ### Installing and Launching
> Follow the instructions to install and launch the exercises from [here](/installation).
> 
> * Download [Docker](https://docs.docker.com/get-docker/). Windows users should choose WSL 2 backend Docker installation if possible, as it has better performance than Hyper-V.
> * Pull the current distribution of Robotics Academy Docker Image:
> 
> ```shell
>   docker pull jderobot/robotics-academy:latest
> ```
> 
> * In order to obtain optimal performance, Docker should be using multiple CPU cores. In case of Docker for Mac or Docker for Windows, the VM should be assigned a greater number of cores.
> 
> ### How to perform the exercise?
> * Start a new docker container of the image and keep it running in the background:
> 
> ```shell
>   docker run --rm -it -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy
> ```
> 
> * On the local machine navigate to 127.0.0.1:8000/ in the browser and choose the desired exercise.
> 
> ### Enable GPU Acceleration
> Follow the advance launching instructions from [here](/installation).

Hi @pariaspe I've updated the pages, are the exercises tested with the new RAM port? should I add it to this PR or can be done later?

**Comment by pariaspe** [comment]
Sorry Pawan, I didn't explain myself correctly before. I would move what it is in `installation.md` now to each exercise. From there, directly link to `gpu_acceleration.md`.

About the port, I'm currently opening it always. There is no problem to open a new port in a docker image. We can added it here or in a different PR, as you prefer.

**Comment by pawanw17** [comment]
Hi @pariaspe I've updated the exercises pages as you described, 
I think it is best to leave installation.md, with the added instructions since a new user would open installation page first before opening an exercise (what do you think?)
I'll create another PR for RAM port

**Review by pariaspe — APPROVED** [review]

**Comment by pariaspe** [comment]
It looks good to me, I'm merging this. Thanks for the contribution! :smile: 
Alright, I'm opening a new issue for adding 7163 RAM port. And yes, the command is ok.

**Pull request merged**
