### PR TITLE
Change GUI to inherit from gui_interfaces and console_interfaces

### PR DESCRIPTION
**Pull request by javizqh**
Changing GUI to inherit from gui_interfaces in order to reduce the amount of duplicated code and boilerplate

### CODE REVIEW

**Comment by javizqh** [comment]
List of exercises switched:

- [x] Autoparking
- [x] Amazon Warehouse
- [x] Follow line
- [x] Obstacle Avoidance
- [x] Global Navigation
- [x] Rescue people
- [x] Basic vacuum
- [x] Loc vacuum
- [x] Follow Person
- [x] 3D reconstrution
- [x] Montecarlo Laser Loc

**Comment by javizqh** [comment]
Both Rescue People and Follow Person have a different GUI implementation, so it will be more challenging to add

**Comment by javizqh** [comment]
For testing is needed to be in the branch of this PR.

How to test:

1. In Robotics Academy modify the line 7 and 8 of the file scripts/mini_RADI/Dockerfile.mini_humble to this:
```docker
RUN mkdir -p /opt/jderobot && \
    git clone --depth 1 https://github.com/javizqh/RoboticsInfrastructure.git -b $ROBOTICS_INFRASTRUCTURE /opt/jderobot
```

2. In Robotics Academy modify the line 12 of the file scripts/mini_RADI/Dockerfile.mini_humble to this:
```docker
RUN mv /opt/jderobot/hal_interfaces /opt/jderobot/gui_interfaces /opt/jderobot/console_interfaces /opt/jderobot/CustomRobots /opt/jderobot/jderobot_drones /home/ws/src/
```

3. In Robotics Academy modify the file compose_cfg/dev_humble_cpu.yaml to this:
```yaml
version: '3.8'

services:
  robotics-academy:
    image: jderobot/robotics-backend:test.4.6.3
    container_name: developer-container
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # devices:
    #   - /dev/dri/card0:/dev/dri/card0
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "7164:7164"
      - "2303:2303"
      - "1905:1905"
      - "8765:8765"
      - "6080:6080"
      - "1108:1108"
      - "7163:7163"
    volumes:
      - type: bind
        source: ./
        target: /RoboticsAcademy
    tty: true
    stdin_open: true
```

4. In the terminal from the root of Robotics Academy go to where the mini_RADI is with:
```bash
cd scripts/mini_RADI/
```

5. Create a mini_RADI with this parameters:
```bash
./build.sh -f -a humble-devel -i add-gui-interfaces -m humble-devel -r humble -t test.4.6.3
```

6. Go back to the root of Robotics Academy:
```bash
cd ../../
```

7. Launch the development enviroment:
```bash
sh ./scripts/develop_academy.sh
```

**Comment by javizqh** [comment]
Here is the part from Robotics Infrastructure: https://github.com/JdeRobot/RoboticsInfrastructure/pull/421

**Comment by pawanw17** [comment]
The changes look fine to me. The exercises will require good testing though. I think we should also move console.py to RI.

Also since you have write access now, in future, I'd suggest pushing changes in a branch of this repo rather than your fork, so it's easier for other reviewers to build the RoboticsBackend just by changing the parameters of the build.sh script

**Comment by javizqh** [comment]
Ok, I will look to move console.py to some kind of Python package or something like gui_interfaces and hal_interfaces

**Review by pawanw17 — APPROVED** [review]

**Review by dduro2020 — APPROVED** [review]
As far as I am concerned, the exercises have already been tested and we can start to simplify GUI.py even more.

**Comment by javizqh** [comment]
I have tested all of the exercises, and all of them work properly

**Comment by javizqh** [comment]
Please merge first this https://github.com/JdeRobot/RoboticsInfrastructure/pull/421 before this one

**Pull request merged**
