### PR TITLE
Changing Threading Gui to Measuring Gui and updating frontend

### LINKED ISSUE #2708: Update rtf measuring to be the same as Unibotics
Update rtf measuring to be the same as Unibotics and change the gui from the exercises to the new measuring one

### PR DESCRIPTION
**Pull request by javizqh**
Do not merge until right before a new Robotics Backend version comes out. For testing is needed to generate a miniRADI wit the following instructions:

```bash
sudo ./build.sh -t adding-rtf
```

### CODE REVIEW

**Review by dduro2020 — COMMENTED** [review]
I'm getting an error on this line, it seems that the .css file is not included.

```js
import "../../styles/visualizers/Frequencies.css";
```

**Comment by javizqh** [comment]
Try cloning the repo again

**Comment by dduro2020** [comment]
More issues with files not found

```js
import monitor from "../../images/monitoring2.png";

```

**Review by dduro2020 — APPROVED** [review]
It now works perfectly

Example:
image

**Pull request merged**
