### PR TITLE
updated GPU acceleration instructions

### LINKED ISSUE #1957: [gh-pages] Update GPU acceleration launch instructions
See #1950

### PR DESCRIPTION
**Pull request by AsRaNi1**
Fixes #1957 
Updated the instructions for GPU acceleration for each exercise according to the changes made in the ``docs/gpu_acceleration.md`` file

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
Some of the exercises you modified don't use the latest RADI (docker image). Please undo the changes in the following exercises:
- Machine vision: RADIv2.4.2
- Mobile manipulation: RADIv2.4.2
- Pick place: RADIv2.4.2
- Follow person: RADIv4.3.0
- Real follow person: RADIv4.3.0 and other devices usage

Despite the instructions are correct for the rest of the exercises, I don't really like the structure of the documentation. In my opinion, there is too much non-relevant info for the student. When a new student kicks in, he/she would probably not interested in GPU acceleration. 
Should we move that info to a different page and link to it in each exercises? What do you think @jmplaza ?

**Review by pariaspe — CHANGES_REQUESTED** [review]
@AsRaNi1 please check "files changed" tab, you are not completely undoing the changes. Thanks

**Comment by AsRaNi1** [comment]
> @AsRaNi1 please check "files changed" tab, you are not completely undoing the changes. Thanks

Yes sorry, i might have missed a little part of the script, i have made the required changes now

**Review by pariaspe — APPROVED** [review]

**Comment by jmplaza** [comment]
- Machine vision: RADIv2.4.2
- Mobile manipulation: RADIv2.4.2
- Pick place: RADIv2.4.2
- Follow person: RADIv4.3.0
- Real follow person: RADIv4.3.0 and other devices usage

All those exercises are deprecated (mobile manipulation, pick & place) or not integrated yet (FollowPerson and real FollowPerson). So I would not care about them now.

**Comment by pariaspe** [comment]
Thanks @AsRaNi1 !

**Pull request merged**
