### PR TITLE
Added Deep Learning Human Detection Exercise

### PR DESCRIPTION
**Pull request by shashwat623**

### CODE REVIEW

**Comment by dpascualhe** [comment]
Looks good! Can you share with me the human detection model you have tested it with? I'll try to replicate results before the meeting.

The only major change needed that I've identified is regarding the exercise documentation. Exercise docs (theory and input/output specifications) must be placed at https://github.com/JdeRobot/RoboticsAcademy/tree/noetic/docs/_pages/exercises/ComputerVision and linked from https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/_pages/exercises.md, so that they can be accessed from the [RoboticsAcademy webpage](http://jderobot.github.io/RoboticsAcademy/exercises/). You can follow as a model the [color-filter exercise docs](http://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/color_filter). Also, I will upload your demo video to the JdeRobot youtube and share with you the link so that you can include it in the webpage.

**Comment by shashwat623** [comment]
@dpascualhe Thank you for your review. I will make the required changes. Also, the demo model I've tested the exercise with is already uploaded inside the `test_model` folder.

**Comment by shashwat623** [comment]
@dpascualhe placed a PR for the exercise webpage on the master branch. Should I go ahead and merge this PR?

**Comment by jmplaza** [comment]
Hold on @shashwat623 , let's @dpascualhe review and merge (or provide feeback) this PR. He is the committer of DL exercises on RoboticsAcademy

**Comment by dpascualhe** [comment]
Hi @shashwat623 I replicated your results, it works smooth :smile: . However, I had to add the exercise to the list of exercises that doesn't have gazebo/ros dependencies in `manager.py` for it to work:
https://github.com/JdeRobot/RoboticsAcademy/blob/507ba70cf6f3f97dad264420c79231dd26da4422/scripts/manager.py#L221-L226

Could you update it?

**Comment by shashwat623** [comment]
> Hold on @shashwat623 , let's @dpascualhe review and merge (or provide feeback) this PR. He is the committer of DL exercises on RoboticsAcademy

Alright @jmplaza

**Comment by shashwat623** [comment]
> Hi @shashwat623 I replicated your results, it works smooth 😄 . However, I had to add the exercise to the list of exercises that doesn't have gazebo/ros dependencies in `manager.py` for it to work:
> https://github.com/JdeRobot/RoboticsAcademy/blob/507ba70cf6f3f97dad264420c79231dd26da4422/scripts/manager.py#L221-L226
> 
> Could you update it?

Hi @dpascualhe , thank you for the review. Good to know it works smooth😁. I have made the required change in `manager.py`

**Pull request merged**
