### PR TITLE
[follow_line]Readme

### PR DESCRIPTION
**Pull request by mohamedsayed18**
added the >> to not overwrite
also the function is called algorithim not excute

### CODE REVIEW

**Comment by jmplaza** [comment]
Hi @mohamedsayed18 ,

your changes in  exercises/follow_line/README.md regarding >> are fine, but your suggested change in docs/_portfolio/follow_line.md is not. Let's stick to "def execute(self):" instead of the proposed "def algorithm(self):". This way it is the same as in other Academy exercises.

In addition we are moving to put the information for each EXERCISE **only** in docs/_portfolio/EXERCISE.md and not in exercises/EXERCISE/README.md. In fact, that README.md should contain only an URL link to the corresponding webpage (whose "source code" is in docs/_portfolio/EXERCISE.md).

Please modify your pull-request. Cheers!

**Comment by mohamedsayed18** [comment]
I edited the function name 
I will make another pull request change the name of the fuction itself in Myalgorithim.py

**Comment by igarag** [comment]
Hi @mohamedsayed18,

The follow line website was modified weeks ago. Can you please verify that your changes are not already included in the documentation?

Regards.

**Comment by mohamedsayed18** [comment]
Hi @igarag 
I think this pull request is no longer valid because the structure of the repo changed a little bit, so I think we can close but I have a recommendation to modifiy the lines
echo 'source /opt/jderobot/share/jderobot/gazebo/gazebo-setup.sh' > ~/.bashrc
echo 'source /opt/jderobot/share/jderobot/gazebo/gazebo-assets-setup.sh' > ~/.bashrc
from > to >> to not overwite data in the bashrc

**Comment by igarag** [comment]
Hi again @mohamedsayed18 .

I include the suggestions in the following pull request. Sorry for the inconvenience.

Regards.

**Comment by igarag** [comment]
Take a look at the result: https://jderobot.github.io/RoboticsAcademy/exercises/follow_line/

**Comment by mohamedsayed18** [comment]
thank you keep up the good work guys

**Pull request closed without merging**
