### PR TITLE
Fix montecarlo laser loc bugs

### LINKED ISSUE #2882: [Monte Carlo Laser Loc] Problem with angle in gazebo <--> map coordinates
Related to #2834.
The conversion functions `GUI.poseToMap` and `GUI.mapToPose` are not transforming the angle properly, it has an offset of 180º.

The converted (x, y) coordinates are fine now, but the angle in map coordinates is wrong (it is not aligned with the X axis).
I think it would be fixed by substracting `pi/2` [here](https://github.com/JdeRobot/RoboticsAcademy/blob/54c7f4fca512f640c6ec0c18839a89ffad2542d5/exercises/static/exercises/montecarlo_laser_loc/python_template/ros2_humble/GUI.py#L90), instead of adding it (and the inverse operation in the other function).

### LINKED ISSUE #2883: [Monte Carlo Laser Loc] Problem with GUI.showPosition
The method `GUI.showPosition` is used to display the "predicted" robot pose. I found 2 issues with this method:

1. The pose is not cleared in the GUI after resetting the exercise. Actually, this problem also happens with the displayed particles (they are not cleared with the reset button).
2. The displayed angle is wrong. The following image shows a simple example where I took the robot's pose from the HAL module and just displayed it with the `GUI.showPosition` method:

show_position_issue

### PR DESCRIPTION
**Pull request by javizqh**
Fix montecarlo laser loc bugs

### CODE REVIEW

**Comment by javizqh** [comment]
@franmore-urjc  Can you test if everything is solved

**Comment by ghost** [comment]
Sorry, but I am afraid I can't. I can't run the local RA version anymore.

I used to be able to run the dev docker compose without having to build the react frontend, but now I cannot do it, and I really don't want to install nvm and yarn in my system for other reasons.

If it helps, the changes look good to me, but I cannot test them.

**Comment by javizqh** [comment]
Okay. For me this solve the issues, so I Will merge It. If the problems still remain, open the issues again

**Comment by javizqh** [comment]
@franmore-urjc In a couple hours there will be a robotics-academy docker image with the tag "test" so that you can confirm if this has been solved

**Pull request merged**
