### PR TITLE
Added Teleoperator mode to follow_line exercise

### PR DESCRIPTION
**Pull request by dhrodao**
Added teleoperator mode to follow_line exercise

### CODE REVIEW

**Comment by ReyDoran** [comment]
Hi, I just tested this branch. Messages seem to be sent (console displays v and w) but the car does not move when using the keyboard arrows.

**Comment by dhrodao** [comment]
I tested it yesterday and it was working. Did you pause the scenario before clicking the teleoperator button?

**Comment by ReyDoran** [comment]
Yes, I tried pausing. The steps I follow in order to test it is: build the image downloading the branch issue-1177 of RoboticsAcademy instead of master, run the image with ./start.sh and load the exercise. I send some code, pause and press teleoperate.

**Comment by dhrodao** [comment]
The problem is pausing, because gazebo physics are also getting paused, so, just press start and then press the teleoperator button, then, you will see that the car stops and you will be able to use the arrow keys.

**Pull request merged**
