### PR TITLE
Fix-#806(modified launch file)

### PR DESCRIPTION
**Pull request by RUFFY-369**
issue #806 
changed the launch file to use drone_assets package's turtlebot3 xacro rather than from copied one

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
Launch fails, xacro file is not found. Please review gazebo environment variables.

fail-856

**Comment by RUFFY-369** [comment]
@pariaspe  for drone_assets package, I don't think that if urdf is as an installation directory?

**Comment by pariaspe** [comment]
> @pariaspe for drone_assets package, I don't think that if urdf is as an installation directory?

I already solved in JdeRobot/drones#78

**Comment by RUFFY-369** [comment]
@pariaspe , yeah saw it, should I close this PR then as you already did it in #857 ?

**Comment by pariaspe** [comment]
Yes, I also close this PR. Thanks for the help :)

**Pull request closed without merging**
