### PR TITLE
added a basic color-filter

### PR DESCRIPTION
**Pull request by Naman-ntc**
Hi, 
This is in reference to #477, I have prepared a minimal working version of my implementation. I thought to make a PR before proceeding forward so we could discuss coding practices, design issues here.

What I have done --
1.) Add roslaunch file for webcam or local video (using video_stream_opencv)
2.) Modified the existing config file to only all ros based input
3.) Removed `local_camera`, `local_video` and `stream_camera` files and replaced with a single `cameraSegment` file.
4.) Updated the GUI in `colorFilter` widget to choose which color-space to work on and sliders for masking out color space.
5.) Added the detection GUI 
6.) Set up a brute force communication between `MyAlgorithm` and `colorFilterWidget` to communicate the slider values

To discuss --
1.) Communication between `MyAlgorithm` and `colorFilterWidget`. Currently I have set up the communication in a bruteforce manner. I store the colorspace bounds in cameraSegment, and as the slider value gets updated, I update the values in cameraSegment object. Since camera is available in MyAlgorithm, the user can read the min/max R/G/B values set in slider and use in his algorithm. Is there any better practice you would suggest for this communication
2.) Are there any general coding practices I should follow?

To be done --
1.) ~~I have not yet implemented the detection GUI and detector communication~~
2.) Clean up code, unnecessary files. Better variable naming, Improve GUI.

Let me know what you guys think about this!

### CODE REVIEW

**Comment by Naman-ntc** [comment]
Hi, I have added the detector module as well. You can find a screenshot of the working code below. I have tried to replicate the GUI from the video on color filter website. 

Below a ROS node has been launched to loads the video (using video_stream_opencv) in the left terminal. It communicates with the `color_filter` node. In color filter widget two a dropdown menu allows switching between RGB space and HSV space for segmentation. A checkbox allows opening the detector's window. Sliders are provided for segmenting out the objects in realtime

Screenshot from 2020-03-22 23-17-01

**Comment by jmplaza** [comment]
Hi @Naman-ntc , it looks nice! 

I would remove the sliders completely and I would add the "play code" button and the JdeRobot logo, as in [other Academy exercises](https://www.youtube.com/watch?v=eNuSQN9egpA). This way it will be a regular exercise: the solution is completely in the student's code. The ColorTuner tool (or others) may be used to get the best values of the color filter, or their effect. This would simplify the communication between parts of the ROS template.

In addition, do not include the solution code in the pull request. We typically store them on a different private repository to avoid the copy-paste from the students :-)

**Comment by Naman-ntc** [comment]
Hi,
The main window does contain play code and the logo (present in the top left corner in my screenshot):
Screenshot from 2020-03-23 00-20-45

Will it be enough? And, I should will the sliders totally from the interface. 

Did I include the solution code somewhere? I just pasted the screenshot right and I ensured `MyAlgorithm.py` is empty before pushing my code

If everything else if fine should I work on exercise documentation and theory? I needed to install ros-melodic-video-stream-opencv separately so it would also need to go in the installation guide.

**Comment by jmplaza** [comment]
Yes, that is more than enough. Just remove the sliders and I will merge your pull-request. We will refine it later if needed.

Yes, feel free to create the webpage for this exercise. Thanks for your contribution!

**Comment by Naman-ntc** [comment]
Hi, I have removed the code for generating the sliders and drop-down menu as you suggested. I will check the exercise webpage

**Comment by nemathahmed** [comment]
Hi, is anyone working on the documentation of the new implementation? With new APIs in the updated exercise, the current readme file seems outdated. I'd be happy to update it if no one is already working on it.

**Comment by igarag** [comment]
Hello.

Thanks for the PullRequest @Naman-ntc .

However, some adjustments are necessary, especially as @nemathahmed  says about the documentation. Although the new structure works with ROS, I had to fix some things so it would be "ready to run" as the repository is cloned. Some of them are:

- Revision of ALL the documentation. It is very outdated and does not specify the steps of installing dependencies or how to launch the infrastructure. For example, the package `ros-melodic-video-stream-opencv` needs to be installed:

```bash
sudo apt install ros-melodic-video-stream-opencv
```

- If as an example you say that you are going to run a video and not the camera, it is necessary to put a link to the video. Here is the link to include it in the documentation review: [video](http://wiki.jderobot.org/store/amartinflorido/uploads/curso/pelotas_roja_azul.avi). I would say to include a comment line in the launch that tells how to run the camera or video. By default, the video will be found in a path on your PC. Setting the value to 0 gives you the camera stream.

- I would add a small solution as an example (correct me if I am wrong and it already exists).

Sorry about the extension. These are the conclusions I drew from the exercise review. Once solved the GUI works very well, simple, clean and intuitive.

If you want to take care of updating the perfect @nemathahmed  documentation. If you have doubts about any step you tell me since I've already been exploring it a bit.

Good work @Naman-ntc.

Nacho.

**Comment by Naman-ntc** [comment]
Hi @igarag, thanks for comprehensive review. 
I have worked a little on the documentation (nothing to concrete) but am constrained with some other commitments till almost end of upcoming week. 
On other issue I would like to mention is that for local videos -- I believe it might also be a good idea to loopback the video by first creating ros-bag for the video file. Since the video starts streaming from opencv even before you run `play code` button, some frames of video are missed which although not substantial is not desirable. Having loopbacks would fix the issue.
I can start working again on documentation by next monday. Till then @nemathahmed you can proceed on the documentation if you want, I'll then look at your documentation and suggest if some improvements are possible.
Thanks,
Naman

**Comment by nemathahmed** [comment]
Hello @igarag and @Naman-ntc 
I've made the changes to the documentation. You can view it [here](https://github.com/nemathahmed/RoboticsAcademy/blob/master/exercises/color_filter/README.md) in my forked repo. I'd like to know if this would work or should I add/remove something. I was thinking of following this up with a small example code and a video for the same. Let me know what you think.
Regards,
Nemath

**Comment by jmplaza** [comment]
Hi, it sounds good to me but I miss the theory section and the hints section (as in [this exercise](https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/obstacle_avoidance)). For instance the color spaces theory (RGB, HSV...) should appear there.

In addition, I would refine this exercise a little bit further. For instance we could:
- [ ] merge all GUI windows into a single one showing the input image, the color filter and the detector image.
- [ ] migrate to python3 instead of the discontinued python2

What do you think?

It is better to avoid code samples @nemathahmed, use links to relevant OpenCV functions in the "hints" section of the exercise webpage.

**Comment by nemathahmed** [comment]
Thank you for the suggestions @jmplaza. I have merged them into one single window and given each subwindow a title. Let me know if this would work.

merged

If this is fine, I can clean up my code and then try migrating to python3. I'll simultaneously add up the theory for the exercise along with hints to relevant functions as suggested by you.
Thanks,
Nemath

**Comment by jmplaza** [comment]
Hi @nemathahmed, just merge also the two windows there, so "play code" button and JdeRobot log are shown too in the single window of the exercise template.

**Comment by nemathahmed** [comment]
To ensure that the live ROS stream is available to the user after he/she stops the code, I've added a small live stream window. If everything is fine, I'll clean up the code and work on the documentation.

Screenshot from 2020-04-17 12-52-22

**Comment by jmplaza** [comment]
Hi @nemathahmed, it sounds good to me.

**Pull request merged**
