### PR TITLE
Fix/regular pressing of backspace #1396

### PR DESCRIPTION
**Pull request by ghost**
Fixes for issue #1396

- Enhances HTML input handling for backspace key (keyCode === 8).
- Prevents default backspace behavior to ensure controlled input.
- Suitable for applications needing precise text manipulation.
- Easily integrated into existing JavaScript projects.

### CODE REVIEW

**Comment by pawanw17** [comment]
Hi @Vrushal7, can you remove the second commit #0304851bf07143f50d3cd633442b5e780ba861f0

**Comment by ghost** [comment]
Hi @pawanw17 ! I tried to remove it but couldn't, since I am facing some issues in the code editor. But changes in both the commits are the same. But if you want I can delete the file from the second commit, should I?

**Comment by pawanw17** [comment]
Actually the first commit adds the function while the second commit just changes some parenthesis positions... The second one isn't required, I think you can use git rebase -i HEAD~2 and drop the second commit

**Review by Apoorvgarg-creator — DISMISSED** [review]
@Vrushal7 A As Suggested by @pawanw17, remove the 2nd Commit

**Comment by pawanw17** [comment]
@Apoorvgarg-creator I tested this, it seems to be breaking the UI

**Comment by Apoorvgarg-creator** [comment]
At what point ?

**Comment by pawanw17** [comment]
Post 
`yarn install && yarn run build`
On opening an exercise it shows a white screen,

**Comment by ghost** [comment]
Kindly review the changes

**Comment by pawanw17** [comment]
@Vrushal7 please test the changes locally... also do the changes as mentioned earlier... we can then reopen this PR.

**Pull request closed without merging**
