### PR TITLE
[Global Navigation] Gui resets properly

### LINKED ISSUE #2541: [Global navigation] Map not reseting
Map not reseting properly

### PR DESCRIPTION
**Pull request by javizqh**
This resolves #2541

### CODE REVIEW

**Comment by javizqh** [comment]
https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/377b0ac9-5a1f-4184-9e8a-7648ee50a070

**Comment by javizqh** [comment]
It resets when the play button is clicked

**Comment by javizqh** [comment]
Now it resets when the reset button is clicked

**Comment by javizqh** [comment]
https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/979fca8a-9d11-43ee-bed9-2c362905fbb9

**Review by pawanw17 — APPROVED** [review]
looks good!

**Pull request merged**
