### PR TITLE
Modifying Vacuums exercise frontend

### PR DESCRIPTION
**Pull request by javizqh**

### CODE REVIEW

**Comment by javizqh** [comment]
New frontend:
Screenshot from 2024-10-04 17-54-58
Screenshot from 2024-10-04 17-57-08

**Comment by javizqh** [comment]
For basic and localized vacuum cleaner

**Comment by javizqh** [comment]
This improves the exercise execution by a substantial amount after the exercise has been executing for more than 5 minutes

**Review by dduro2020 — APPROVED** [review]
Perfect, the route is now much more defined and cleaner.

**Pull request merged**
