### PR TITLE
Added Animated Logo in README

### LINKED ISSUE #1712: Animated Logo in README
Add Animated Logo in README.md

### PR DESCRIPTION
**Pull request by akshaynarisetti**
As part of the README Revamp process, I added an Animated Logo to the README

fixes #1712

### CODE REVIEW

**Comment by akshaynarisetti** [comment]
Hi @pariaspe 👋 , check this out!

For Reference, this is how the README looks after adding an Animation to Logo.

https://github.com/akshaynarisetti/RoboticsAcademy/blob/master/README.md

**Comment by jmplaza** [comment]
Static simple logo is fine, animated logo is nice, but I'm not sure whether or not we need the advertisement link to https://mmg-ai.com/en/ here. I would say the simpler the better...

**Comment by akshaynarisetti** [comment]
@jmplaza sure, but regarding the advertisement link it was already there in the README.

Do you want me to remove that link?

**Comment by akshaynarisetti** [comment]
Hi @jmplaza, now the URL is changed to the JdeRobot Organization's webpage

**Pull request merged**
