### PR TITLE
Fix digit classifier bugs and format

### LINKED ISSUE #1117: Digit classifier exercise freezes after detecting the first digit
Only happens when launching through the django server

### PR DESCRIPTION
**Pull request by dpascualhe**
Closes #1117 and #1102

### CODE REVIEW

**Review by ReyDoran — COMMENTED** [review]
Hi, where can I get a sample .onnx file to test? Everything else seems to be working fine though.

**Comment by dpascualhe** [comment]
hi @ReyDoran ! I've just uploaded an [example model](https://github.com/JdeRobot/RoboticsAcademy-extra/blob/d9fb61619478629090f811c21e8f8a036380f382/solutions/dl_digit_classifier/mnist_cnn.onnx). Also, I've disabled the buttons that can't be used in the exercise (save/load/reset) until we have a custom base html file for the deep learning exercises (we're working on it).

**Comment by ReyDoran** [comment]
The exercise is disconnecting after I press Play button. I started an 3.1.3 container with --device /dev/video0:/dev/video0 and copied the issue-1117 branch inside the container. Am I missing a step?

**Comment by dpascualhe** [comment]
@ReyDoran I've tested the exercise after building a Docker image from the Dockerfile-noetic-3.1 and runs smoothly for me. Is there any difference with respect to the 3.1.3 image pushed to Docker hub? I'll try to replicate your issue with the 3.1.3 image and let you know.

**Comment by dpascualhe** [comment]
@ReyDoran I think I might know what the issue is! We detected a few weeks ago that sometimes, when using Chrome, the exercise crashed while decoding the uploaded model (#974). Can you try with other browser (I'm on Firefox right now) and validate if that's your issue? I will take a look into it and try to solve it before merging.

**Comment by ReyDoran** [comment]
Oh, that's it. I can confirm that in Firefox is working correctly, and in Chrome is crashing after clicking play.

**Comment by ReyDoran** [comment]
May I merge this pr and open a new issue for the Chrome browser error?

**Comment by dpascualhe** [comment]
Sure! Chrome browser issue is already opened in #974

**Pull request merged**
