### PR TITLE
Issue-1763

### PR DESCRIPTION
**Pull request by Zekrom-7780**

### CODE REVIEW

**Comment by dpascualhe** [comment]
@Zekrom-7780 can you attach here in a comment the appearance of the exercise before and after this update? Thanks!

**Comment by Zekrom-7780** [comment]
[The updated graph](https://drive.google.com/file/d/130ItkRnu8ivlnQdgg1CiD_ChCKmuRPtS/view?usp=sharing)

[The Original Graph](https://drive.google.com/file/d/1gAUs8PBsqzXiTvjaSOnRuVBOodRg9bAh/view?usp=sharing)

**Comment by dpascualhe** [comment]
from my local test:
image

**Review by dpascualhe — APPROVED** [review]
from my local test
image

**Pull request merged**
