### PR TITLE
Update montecarlo frontend

### PR DESCRIPTION
**Pull request by javizqh**

### CODE REVIEW

**Comment by javizqh** [comment]
Screenshot from 2024-10-10 18-09-21

**Comment by javizqh** [comment]
Missing change on resize

**Comment by javizqh** [comment]
Ready to check

**Comment by javizqh** [comment]
Ready to check

**Review by dduro2020 — APPROVED** [review]
Perfect, also with an RTF of 1.0

**Review by dduro2020 — CHANGES_REQUESTED** [review]
The second vacuum should not appear.

**Pull request merged**
