### PR TITLE
Fix: Update RADI latest version in compose_cfg

### LINKED ISSUE #2594: Update Robotics Academy Image in compose_cfg
Currently, The latest development version of  ~~RAM~~ RADI is **4.5.13**

But In **Yaml** files present inside **compose_cfg** is pointing to **4.5.9**

### PR DESCRIPTION
**Pull request by Apoorvgarg-creator**
Fix #2594

### CODE REVIEW

**Comment by pawanw17** [comment]
Hi, 4.5.14 is already released, can you update the same

**Comment by pawanw17** [comment]
Also we need a better way to update these versions

**Comment by Apoorvgarg-creator** [comment]
> Also we need a better way to update these versions

I was also thinking the same

**Comment by javizqh** [comment]
I have updated the version from 4.5.13 to 4.6.1 which is the latest

**Review by pawanw17 — APPROVED** [review]

**Comment by Apoorvgarg-creator** [comment]
But let's keep the issue open for dynamically changing this.

**Pull request merged**
