### PR TITLE
Updating amazon warehouse frontend

### PR DESCRIPTION
**Pull request by javizqh**

### CODE REVIEW

**Comment by javizqh** [comment]
Missing resize and draw target

**Comment by javizqh** [comment]
Missing changing vehicle model to fit the ackermann one

**Comment by javizqh** [comment]
If possible test in Unibotics before merging. The names of the universes may cause error

**Comment by dduro2020** [comment]
It works perfectly, but I think it would be a good idea to modify the image of the robot on the map for when the robot stands up, maybe by putting a black circle in the centre or some other way that is visually understandable.

**Comment by javizqh** [comment]
I will create a new issue

**Pull request merged**
