### PR TITLE
Follow line web-template README.md modified 

### PR DESCRIPTION
**Pull request by NayOoLwin5**
This is in reference to #600

### CODE REVIEW

**Review by SakshayMahna — COMMENTED** [review]
Hello Nay!
One thing you can do in order to completely improve this README.

Possibly, you must be following instructions from the Docker-Hub page. [This one](https://hub.docker.com/r/jderobot/robotics-academy)

Try adding all the instructions from the Docker-Hub README to this README. In this way, we may have the complete instructions on how to run this exercise using Docker.

**Comment by SakshayMahna** [comment]
I also just realized in case of Windows the IP address passed with the `python host.py` is **not** of the form `192.168.x.x`.

In place of that it is `172.17.0.2` in my case. This is present in the file `/etc/hosts` in the Docker container.

Capture

**Comment by NayOoLwin5** [comment]
Hi @SakshayMahna,
I updated the README file. Please have a look at it.

I wasn't using docker container at first . But I still needed to pass the IP address 127.0.0.53 on my native linux for the established connection.
Running `cat /etc/hosts` on linux without docker doesn't show any IP address. Therefore I included `cat /etc/resolv.conf` in README file which also shows the wanted IP address .

Later,I tested docker container on linux machine on which the IP address shown with the command `cat /etc/hosts` is same 172.17.0.2 as yours.
Screenshot from 2020-09-20 07-27-54
It seems it is same on any machine if you are using the docker container

**Comment by SakshayMahna** [comment]
Great! I am merging the PR now.

**Pull request merged**
