### PR TITLE
RViz2 web template for ROS2 RADI

### PR DESCRIPTION
**Pull request by trunc8**
### Steps to replicate
Steps to replicate as well as video of expected behavior have been mentioned in [this blog post](https://theroboticsclub.github.io/gsoc2021-Siddharth_Saha/milestones/2021/07/01/week-6)

For reference, the step are as follows
```sh
git clone https://github.com/trunc8/RoboticsAcademy.git
cd RoboticsAcademy/scripts
git checkout issue-801
./build.sh
docker run -it \
      --rm \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      --name foxy_radi_container \
      -v $PWD/../:/RoboticsAcademy \
      -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 6081:6081 -p 1108:1108 \
      foxy-radi ./start.sh
```
- Click the Django server URL presented
- Click the Turtlebot3 Map Building exercise
- Press connect
- After successful connection, press the Rviz button followed by the Gazebo button
- RViz, the Turtlebot3 world and the bot should be visible
- Press the console button and run `ros2 run turtlebot3_teleop teleop_keyboard` to teleoperate the bot

### Comments
Introduces a map-building exercise named tb3_nav. This exercise enables us to test the RViz connections.

Solves Issue #801   
Also solves Issue TheRoboticsClub/gsoc2021-Siddharth_Saha#6

### CODE REVIEW

**Review by pariaspe — COMMENTED** [review]
It connects and works fine. 
I'm interested to know why you mount two new volumes (`/tmp/.X11-unix:/tmp/.X11-unix` and `$PWD/../:/RoboticsAcademy`). Notice that the second one forces to run the cmd from `scripts` dir

**Comment by trunc8** [comment]
Hi @pariaspe, the first mount (`/tmp/.X11-unix:/tmp/.X11-unix`) solves the below error message when the connect button is pressed. This error may be specific to my system's hardware. I am not sure of that.
```
_XSERVTransmkdir: ERROR: Cannot create /tmp/.X11-unix
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 17
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
```


The second mount (`$PWD/../:/RoboticsAcademy`) is only for **testing** as the new exercise files have not been pushed to the official `foxy` branch. Once they are pushed, `git clone` would update the files in the Docker image automatically, and this mount won't be necessary.

**Comment by pariaspe** [comment]
Thanks for the clarification. 

I've just tested the first mount and it isn't needed in my machine. Let's explore that error, some users may face the same.
Ok, good to know about the second mount.

For my part, go ahead with the merge

**Comment by ReyDoran** [comment]
Working correctly on both non-accelerated and accelerated Ubuntu hosts

**Review by ReyDoran — APPROVED** [review]

**Pull request merged**
