### PR TITLE
solved Issue #1910 [follow_line] Model visual details not displaying well

### PR DESCRIPTION
**Pull request by GauravKumar9920**
I have updated the models in the world file with f1_renault.

### CODE REVIEW

**Comment by GauravKumar9920** [comment]
@pariaspe can you please review this PR, Thankyou !

**Comment by pariaspe** [comment]
Hi, your solution looks good, but I want to test it properly. If everything works fine, it will be merged by this weekend. Did you test the new model? Is it moving and sending images to the GUI?

**Comment by GauravKumar9920** [comment]
> 

Is there any code available so that I can upload it into the bot and test the other aspects of it like you mentioned......
I have tested if the bot is spawning correctly in every circuit.

**Comment by pariaspe** [comment]
> Is there any code available so that I can upload it into the bot and test the other aspects of it like you mentioned...... I have tested if the bot is spawning correctly in every circuit.

Try something like:
```python
from GUI import GUI
from HAL import HAL
# Enter sequential code!

while True:
    # Enter iterative code!
    img = HAL.getImage()
    GUI.showImage(img)
    HAL.setW(0.1)
```

**Comment by GauravKumar9920** [comment]
I tested the model it's moving and sending the images to GUI.

**Review by pariaspe — APPROVED** [review]
Approved, waiting to merge since its include changes from #1909

**Comment by GauravKumar9920** [comment]
> Approved, waiting to merge since its include changes from #1909

I would do that now !

**Comment by GauravKumar9920** [comment]
Hey @pariaspe I have committed the changes and kindly have a look at them.

**Comment by pariaspe** [comment]
Hey, you got me wrong I guess. You are nesting PRs. Go to "Files changed" tab and see all the changes you are proposing in this PR. As you can see you are including changes for #1900 and for #1910, while it should only include for the second one. The rule is easy, for each issue at least one pull request.
I expect to finish reviewing #1909 today, so please wait until that PR is reviewed.

**Comment by GauravKumar9920** [comment]
I'm sorry, I have recently explored git hub to this scale, I made a few mistakes in my local repo at first, I am making sure it's not happening again, also I thought you were asking me to merge the changes I had made to the previous issues, cause previously I wrote it solved this issue as an follow up with the issue #1900, that time I didn't knew how to contribute to an org with GitHub exactly so  I made a few mistakes, I promise for the next issue onwards this issue of nesting won't occur kindly bear with me with this one as I'm still learning and exploring daily, also what Shall I do now with the changes I made currently ?

I previously was thinking when the issue #1900 gets merged I will update the branch of the current issue, However I misunderstood the assignments 😅

Won't happen again.

**Comment by pariaspe** [comment]
> I'm sorry, I have recently explored git hub to this scale, I made a few mistakes in my local repo at first, I am making sure it's not happening again, also I thought you were asking me to merge the changes I had made to the previous issues, cause previously I wrote that this issue was solved as an follow up with the issue #1900, that time I didn't knew how to contribute to an org with GitHub exactly so I made a few mistakes, I promise for the next issue onwards this issue of nesting won't occur kindly bear with me with this one as I'm still learning and exploring daily, also what Shall I do now with the changes I made currently ?
> 
> I previously was thinking when the issue #1900 gets merged I will update the branch of the current issue, However I misunderstood the assignments sweat_smile
> 
> Won't happen again.

Don't worry, I just wanted to clarify the misunderstanding. Leave the changes as they are now, as soon as I go through #1909, I'll merge both.

**Comment by pariaspe** [comment]
Hey @GauravKumar9920 , just as a demonstration on my previous statement. If I go ahead and merge this PR directly, I'll be pushing to main some unwanted changes (the minus sign you changed in #1909, but not here). Do you understand why is important to keep PR uncorrelated?

**Review by pariaspe — APPROVED** [review]

**Comment by GauravKumar9920** [comment]
Yes @pariaspe I understood, it's a learning experience for me and thanks for all the guidance looking forward to contribute to Robotics Academy :)

**Pull request merged**
