### PR TITLE
[Obstacle avoidance] Updated excercise 

### LINKED ISSUE #2544: [Obstacle avoidance] Not receiving images from camera
It does not receive the images from the camera topic and it gets stuck infinitely.
It happens randomly so more testing is needed to find why it happens

### PR DESCRIPTION
**Pull request by javizqh**
This resolves #2544.
Also has the following changes:

- Removing interfaces in order to use hal_interfaces
- Removing odometry from map
- Removing image because of what is explained in #2544 
- Using real distances for the areas displayed
- Removing unnecessary threads in the GUI

### CODE REVIEW

**Comment by javizqh** [comment]
Linked with this [PR](https://github.com/JdeRobot/RoboticsInfrastructure/pull/389).

**Comment by javizqh** [comment]
Here are the improvements in my setup:

- CPU: Intel i9-13900HX 32 core
- GPU: NVIDIA 4060 laptop
- RAM:  64,0 GB

|  | Original | Without displaying image | Without camera | Without camera & With GPU (Usage 35%) |
| -------------| ------------- | ------------- | ------------- |------------- |
| Gz Client  (Cpu usage %) | 600 | 600 | 600 | 60 |
| Gz Server (Cpu usage %) | 600 | 600 | 100 | 60 |
| Fps  (More = Better)          | 8 | 8.5 | 10 | 60 |
| RTF   (More = Better)         | 0.7| 0.73 | 0.8 | 1 |

**Comment by pawanw17** [comment]
We may have to update the documentation since some methods are removed

**Comment by javizqh** [comment]
The documentation is already updated in here https://github.com/JdeRobot/RoboticsAcademy/pull/2546

**Comment by jmplaza** [comment]
Good to see an increase in RTF from 0.7 to 0.8 on the same exercise. This optimization and those coming increase the usability of RoboticsAcademy, even in not so fast computers.

**Review by pawanw17 — APPROVED** [review]

**Pull request merged**
