### PR TITLE
On Demand Gzclient

### PR DESCRIPTION
**Pull request by SakshayMahna**
In reference to issue #903 

Only for Follow Line exercise

### CODE REVIEW

**Comment by SakshayMahna** [comment]
@ReyDoran could you please check this PR, if this works for accelerated machines?

Only for Follow Line exercise. The terminal reports the whether gzclient is going to start or going to close.

**Comment by ReyDoran** [comment]
Hardware acceleration is working. I can see gzclient starting but not closing though (on both accelerated and non-accelerated).

**Comment by SakshayMahna** [comment]
Okay thanks! I'll have a look.

**Comment by SakshayMahna** [comment]
Now it's working.

**Comment by ReyDoran** [comment]
Nice, working correctly on accelerated version too!

**Pull request merged**
