### PR TITLE
Display Real time factor in the follow_line's exercise webpage

### PR DESCRIPTION
**Pull request by trunc8**
Solves Issue #843 
image
This is how the final render looks(compare RTF in the table and in Gazebo VNC). I have described my changes via verbose commit messages.

### CODE REVIEW

**Comment by SakshayMahna** [comment]
I will review the PR and let you know the details.

**Comment by SakshayMahna** [comment]
Extracting the RTF from gz stats seems good to go!

But, there is one thing; try including the RTF message in the `frequency_message` dictionary and the sending part to `send_frequency_message` function itself. This would also result in an appropriate change to the `ws_code.js` file. 

This would maintain uniformity in the messages being transferred through the websockets(Single JSON packets containing relevant information)

**Comment by trunc8** [comment]
Cool! That was actually the first version that I had implemented and got working. But the nomenclature seemed off. Naming it as "stats" generalizes if we want to display simulation and real-time in the future. Shall I modify it back as part of the frequency_message?

**Comment by SakshayMahna** [comment]
Since, it's a single simulation based message, we can work with the naming convention for now. On addition of more such simulation elements, the `frequency_message` would be renamed to something like `control_message`.

According to the design, the code websocket has two functions, exchanging the student's code and exchanging the control messages(that's why the control message rename would be appropriate)

**Comment by trunc8** [comment]
Yup, that makes sense. I will include it as part of `frequency_message` for now. What is the organization's preference at such times? Shall I amend the last commit `758184f` and force push the modified commit on my branch `issue-843`? This will keep our master branch's commit history cleaner.
Or shall I simply add a new commit to `issue-843`?
[Reference- Options 1 and 2](https://www.burntfen.com/2015-10-30/how-to-amend-a-commit-on-a-github-pull-request)

**Comment by SakshayMahna** [comment]
You can simply, add a new commit to the branch.

**Comment by jmplaza** [comment]
We may even show the Gazebo RTF continuous measurements in the frontend just in the place of "DebugLevel widget". which may be safely removed. With the enhanced console (based on the vnc display), it makes no sense. It should be implemented by the students on their own code in case of being interested on several levels for debugging messages.

**Comment by trunc8** [comment]
I have removed the debug-level widget and enforced a single JSON message in separate commits. I have verified that the bot completes a lap with the present changes. Requesting one of the maintainers to review the changes.

**Comment by SakshayMahna** [comment]
Great! The changes look good to go!

There is just a slight concern, since the removal of Debug Window would require us to keep both the repository and the RADI image up to date, we may merge these changes after the 0.3.14 RADI image has been released. The release would be updated in just a couple of days.

**Pull request merged**
