### PR TITLE
Follow_road_v2.3(check for errors)

### PR DESCRIPTION
**Pull request by RUFFY-369**
Migration of follow_road from v2.1 to v2.3 (error to resolve)
Refer issue #859

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
Hi @RUFFY-369,

Your PR seems to be OK, but I'm requesting some minor changes.
- Dockerfile follow_road dependencies not needed. Already installed.
- World file is duplicated. Please remove the one in launch dir.
- World also has to be improved. Drone starting pose is incorrect, jderobot logo is over the road, house model is not loaded..
- I was also thinking to make a circular road (just joining the current end with the current start). If this is implemented, it will be nice to indicate somehow the init-end of the circuit.
- Exercise should be included in RoboticsAcademy.html
- README.md should be updated with new developers instructions (vnc+gzclient). Don't worry with this by now.

follow_road_23

About your error, remember to build a new RADI (robotics academy docker image) locally with your proposed changes within.

**Comment by RUFFY-369** [comment]
Hi @pariaspe,Thank you for the review.

1. Yeah, I will make the required changes in the mentioned files (wasn't able to confirm the spawning position of logo due to my error)

2. And also I had some changes in mind to improve upon the visualisation & functionality of the exercise, so, before that I will commit the mentioned changes.

3. And regarding the solution you suggested for my error, I actually tried building the RADI after the changes in exercise & files but the error was still persisting. Anyways, I will try to build it again &lets see how it goes.

**Comment by RUFFY-369** [comment]
Hi @pariaspe ,
Here the changes committed in brief:
1. Minor changes done as mentioned by you (new developer instructions still remain to add in README.md)
2. World file has been changed and a closed loop in the form of a road has been made for iris model drone to follow. Few extra models such as 'house_4', 'polaris_ranger_xp900' & 'person_standing' have been added for more appealing world & also the sky & clouds have been added.

Kindly review the changes.

Regards,
RUFFY-369

**Comment by pariaspe** [comment]
Hi @RUFFY-369,

Have you tested the exercise? Something seems to be wrong in the world, which is not loaded well (vnc is connected but the window remains black). I've also checked the world and, personally, I wouldn't add so many models to the world.

**Comment by RUFFY-369** [comment]
Hi @pariaspe ,
When I tested it I was getting a black screen with loading signal but the world wasn't loaded. I assumed that it may be due to performance issues as a model was being trained in parallel in my system while testing the exercise.
Now, I am again getting the same loading signal with black screen with a 'connection closed' message. (Any suggestions to resolve)

In the recent commit, I removed the redundant models from the world file. It would be great if you could test it out on your system to see if issue is being reproduced.

**Comment by pariaspe** [comment]
Hi @RUFFY-369,

Sorry for the late response. I've been testing your PR and figuring out why does the black screen error happens. It seems to be a problem with a model that gazebo don't find locally, so it tries to get it from the Gazebo Model Database server. This takes quite a long time and during this the gazebo world doesn't load (black screen). After getting all the models from the server, the exercise seems to be OK. Notice that this just happens with this exercise, so the bug it isn't in the RADI.

I may be wrong, but I think that the problematic model may be _house_3_. Try to launch the exercise without this model (or other if the problem persists).  I propose you to fix the minor bug before merging the PR. 

Thanks!

error

**Comment by RUFFY-369** [comment]
Hi @pariaspe ,
1. I have solved the issue of 'black screen' by replacing the '_house_3_' model with '_gas_station_' model. As you mentioned that the house_3 is being retrieved from Gazebo Model Database server, it seems that it is the case. I cross checked it by using it with 'follow_turtlebot' exercise and got the black screen as expected.
Screenshot from 2021-04-26 18-48-53

2. The 'gas_station' model doesn't cause this issue and spawns well.
Screenshot from 2021-04-26 20-16-28

3. I have also added a check button for developer instructions in the exercise.html, same as to 'follow_turtlebot'. The reason being that on my system, the process was killed as soon as I clicked the connect button. And also the checkbox can come in handy too.

4. I have also updated the developer instructions for the exercise as well.

Screenshot from 2021-04-26 20-22-27

Kindly test the recent commits and please inform me if any bug comes up, before the merge.

Regards,
Prakarsh

**Comment by pariaspe** [comment]
Hi @RUFFY-369,

Your PR seems to be OK, so I'm merging it to master. There are still a few things to do. The RADI is evolving these weeks in order to improve the performance, so it might affect to all the current exercises, which might need an update in a couple of days. 
Also, we usually collect all the models used in the exercises in a ROS package: [drone_assets](https://github.com/JdeRobot/drones/tree/master/drone_assets). Feel free to open an issue in that repository and propose a PR solving it. 

Thanks, we already have three drone exercises in v2.3! 🎉🎉🎉

**Comment by RUFFY-369** [comment]
Hi @pariaspe ,
Thank you for the merge. As for the future needed update, I will look into it.
And also I will propose a PR in drone_assets for the gas_station model as soon as possible.

Regards, 
Prakarsh

**Pull request merged**
