### PR TITLE
add play,pause and reset buttons to control ground turtlebot

### PR DESCRIPTION
**Pull request by iamarkaj**
issue #806

### CODE REVIEW

**Comment by iamarkaj** [comment]
Hi @pariaspe 
please review this

**Comment by pariaspe** [comment]
Thanks @iamarkaj, your PR works well.

Just one comment, previous to migration to v2.3 the turtlebot started to move after launch. This behavior was kept after migration, but since we have buttons now, it would be better to start moving the turtlebot after pushing play button. This also extends to reset button, which resets turtlebot position well but does not stop the robot.

**Comment by iamarkaj** [comment]
Hello @pariaspe the turtlebot does not start automatically now, but for the first time the play button is pressed, it waits for few seconds before playing

**Review by pariaspe — APPROVED** [review]
Looks nice, thanks @iamarkaj

**Pull request merged**
