### PR TITLE
Fixed some Typos and Spelling mistakes in the Exercises docs.

### PR DESCRIPTION
**Pull request by vikaskumareinstein**
I am starting out . So , I tried fixing some typos and spelling mistakes in the Exercise documentation.

### CODE REVIEW

**Review by SakshayMahna — CHANGES_REQUESTED** [review]
Hello!

The changes seem good to go! But there are a few things that need to be addressed:

1. Please delete/remove the last two commited files of this PR(there seems to be a folder called `exercises/vacuum_cleaner/web-template`, you may simply delete that). I am currently working on it, so shouldn't be appropriate to add these at the moment.

2. Create an Issue with a similar title, and reference that in this PR. After we have merged the PR, we may delete the issue. This is the standard procedure that we follow before merging any PR on this repository.

**Comment by vikaskumareinstein** [comment]
I will do the changes as suggested....

**Comment by vikaskumareinstein** [comment]
Hi @SakshayMahna I think I have done the required changes.I have deleted the second-last commit as suggested, and now only one commit with the typos remains.

**Comment by SakshayMahna** [comment]
Great!

This is in reference to issue #648 .

**Pull request merged**
