### PR TITLE
Update vacuum_cleaner.launch

### PR DESCRIPTION
**Pull request by SakshayMahna**
This is in reference to issue #376 
The world file named `Vacuum.launch` does not exist. Instead, `roomba_1_house.world` is the actual world file that should be run. The corresponding change has been made to `vacuum_cleaner.launch`.

### CODE REVIEW

**Comment by mohamedsayed18** [comment]
i changed the world to roomba_1_house.world but still have the same error

**Comment by SakshayMahna** [comment]
What is your exact error?
I made the changes in `vacuum_cleaner.launch`
```bash
<arg name="world_name" value="roomba_1_house.world"/>
```

**Comment by mohamedsayed18** [comment]
the same error except for the name of the file
before changing 
> [Wrn] [FuelModelDatabase.cc:248] URI not supported by Fuel [Vacuum.world]
> [Wrn] [SystemPaths.cc:459] File or path does not exist [""] [Vacuum.world]
> [Err] [Server.cc:382] Could not open file[Vacuum.world]
> [Wrn] [Server.cc:341] Falling back on worlds/empty.world
> [ INFO] [1578232123.825084646, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
> [ INFO] [1578232123.852963224, 0.049000000]: Physics dynamic reconfigure ready.
> [Err] [InsertModelWidget.cc:433] Missing model.config for model "/opt/ros/melodic/share/turtlebot3_gazebo/models/turtlebot3_autorace"
after making change

> 
> [Wrn] [FuelModelDatabase.cc:248] URI not supported by Fuel [roomba_1_house.world]
> [Wrn] [SystemPaths.cc:459] File or path does not exist [""] [roomba_1_house.world]
> [Err] [Server.cc:382] Could not open file[roomba_1_house.world]
> [Wrn] [Server.cc:341] Falling back on worlds/empty.world
> [ INFO] [1578232338.459510012, 0.023000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
> [ INFO] [1578232338.490466519, 0.051000000]: Physics dynamic reconfigure ready.
> [Err] [InsertModelWidget.cc:433] Missing model.config for model "/opt/ros/melodic/share/turtlebot3_gazebo/models/turtlebot3_autorace"

**Comment by SakshayMahna** [comment]
The directory path `/opt/jderobot/share/jderobot/gazebo/worlds/` should contain the file `roomba_1_house.world`. Does this directory path contain the file in your local computer?

**Comment by mohamedsayed18** [comment]
it is working now maybe there was a problem with my installation yesterday 
I'm very sorry about this.
just a small note maybe helpful I got this error in terminal but the model loads fine
 [Err] [InsertModelWidget.cc:433] Missing model.config for model "/opt/ros/melodic/share/turtlebot3_gazebo/models/turtlebot3_autorace"

**Comment by SakshayMahna** [comment]
Yes, this error is still there, but causes no problem with the execution of the exercise. This error may be resolved by downloading turtlebot3 packages externally.

**Pull request merged**
