### PR TITLE
Django webserver inside RADI - Issue 875

### PR DESCRIPTION
**Pull request by ReyDoran**
Includes a Django server which serves the exercise pages. It will allow refactoring web templates to share common parts and making easier to update the frontend ([issue-813](https://github.com/JdeRobot/RoboticsAcademy/issues/813)). The main change in the folders structure is that the previous exercises/ content is now within exercises/static/exercises/, as Django is serving it. Also, RoboticsAcademy.html is now a Django template and is located in exercises/templates/exercises/.
Exercises are now added by placing the folder exercise_name inside exercises/static/exercises and inlcuding it in db.sqlite3. This can be done by using the Django admin site:
1) Start the server
python3.8 manage.py runserver
2) Log in to the admin site. In the browser go to 127.0.0.1/admin, account “user”, password “pass”.
3) Click 'new exercise' and fill: exercise id (folder name), name (name to display), state (active), language, and description (description to display). Save and exit.
4) Commit db.sqlite3 changes to the repository.

The RADI can be launched now with this command:
docker run -it -p 8000:8000 -p 8080:8080 -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy ./start.sh
and it will run both the Django webserver and the Robotics Academy backend (manager.py). The RoboticsAcademy.html will be available in the browser at 127.0.0.0:8000.
If the RADI is launched with the old command:
docker run -it -p 8080:8080 -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy  python3.8 manager.py
it will only run the backend.

### CODE REVIEW

**Comment by trunc8** [comment]
Hi, I pulled the latest RADI image and executed `docker run -it -p 8000:8000 -p 8080:8080 -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy ./start.sh`. But I get the following error message:  `/ros_entrypoint.sh: line 6: /start.sh: No such file or directory`  
I examined the Docker image, and the `start.sh` does seem to be missing at the root directory. Have the instructions changed since this PR?
Thanks!

**Comment by iamarkaj** [comment]
I think you need to run `docker build` first.

**Comment by trunc8** [comment]
Thanks, @iamarkaj. That worked!
The latest version of RADI (`jderobot/robotics-academy`) does not reflect these changes yet. As a temporary reference for other developers before the release of the next RADI, here are the steps that worked:
- `cd RoboticsAcademy/scripts`
- `docker build -t jde_image .`
- `docker run -it -p 8000:8000 -p 8080:8080 -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jde_image ./start.sh`

**Comment by pariaspe** [comment]
Hi guys,
That's weird, latest RADI (v2.3.17) has been pushed 11 days ago. It might have some bug then. Maybe @SakshayMahna can help us.

**Comment by jmplaza** [comment]
Hi @trunc8 , the new RADI is about to come. It will include most recent improvements regarding #923, #914, #901, #875 and #813

**Pull request merged**
